pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    embedding: speechbrain/spkrec-ecapa-voxceleb
    embedding_batch_size: 16
    embedding_exclude_overlap: true
    segmentation: pyannote/segmentation@2022.07
    segmentation_batch_size: 16

params:
  clustering:
    method: centroid
    min_cluster_size: 15
    threshold: 0.7
  segmentation:
    min_duration_off: 0.5
    threshold: 0.5
